### PR TITLE
Bugfix/loading indicator out of container

### LINKED ISSUE #144: Loading animation is placed in the wrong DOM section
The loading animation is placed at the bottom of the main DOM tree instead inside the `<article class="application--root"`>. 

WRONG: 
bildschirmfoto 2018-05-23 um 09 23 06

CORRECT SUGGESTION:
bildschirmfoto 2018-05-23 um 09 24 04

### LINKED ISSUE #151: Do we need overflow: auto?
Do you need `overflow: auto` or was it just implemented as "circuit breaker" (defensive programming)? I think we can remove it. If not, we need to find a solution as AEM should not have to override SPAs css. Happy for FB. 

mai-23-2018 14-44-47

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #144 
fixes #151

### CODE REVIEW

File: src/components/App.js [hunk 1]
```diff
@@ -1,5 +1,4 @@
 import React, { PureComponent } from 'react'
-import { Portal } from 'react-portal'
```
Comment (LucaMele) [inline src/components/App.js]: please remove the package.json dependecy if not needed
