### PR TITLE
fixed ovverride of selected prop

### LINKED ISSUE #26: Radio/SegmentedItem does not change selected state
radio-selected-not-updated

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #26 

The radio is broken because the `Field`s **props** property overwrites all other properties passed to field, if they exists.
Docs: https://redux-form.com/7.2.3/docs/api/field.md/#-code-props-object-code-optional-

### CODE REVIEW

File: src/components/radio-buttons/RadioButtons.js [hunk 1]
```diff
@@ -98,7 +98,7 @@ export default class RadioButtons extends PureComponent {
           {label}
         </label>}
         <div className={radioButtonsOptionsClasses}>
-          {options && options.map((option, index) =>
+          {options && options.map(({ selected, ...option }, index) =>
             (
               <Field
```
Comment (AndyOGo) [inline src/components/radio-buttons/RadioButtons.js]: @LucaMele 
@lina-salih 
Using `props` of Field overwrites all props with initial payload (which also includes `selected` state, hence updates of `selected` property never get through).

Comment (AndyOGo) [reply src/components/radio-buttons/RadioButtons.js]: Btw, any prop passed to Field will be automatically forwarded to to Field's component - using `props` shouldn't be needed.
> This construct is completely optional; the primary way of passing props along to your component is to give them directly to the Field component, but if, for whatever reason, you prefer to bundle them into a separate object, you may do so by passing them into props.
